apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app-container
          image: lohsuan/todo-app:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8888"
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://todo-db-clusterip:27017/mongo"
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20