# github action to run ci/cd pipeline on push
name: build-test-deploy

on:
  # push:
  #   branches:
  #     - main
  #     - feat*
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      # - name: Download previous coverage report
      #   uses: actions/download-artifact@v4 
      #   with:
      #     name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }} 


      # - name: Display structure of downloaded files 
      #   run: ls -R

      - shell: bash
        run: |
          cd backend
          value=`cat last_coverage.txt`
          PREVIOUS_COVERAGE=$(echo $value)
          echo "Previous Coverage: $PREVIOUS_COVERAGE"
          echo "$PREVIOUS_COVERAGE" > $GITHUB_OUTPUT
        id: previous_coverage

      - name: Run tests
        run: |
          cd backend
          npm run test
      
          COVERAGE_PERCENTAGE=$(cat coverage/index.html | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
          echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
          PREVIOUS_COVERAGE=$(cat ${{ steps.previous_coverage.outputs.GITHUB_OUTPUT }})

          if (( $(echo "$COVERAGE_PERCENTAGE < $PREVIOUS_COVERAGE" | bc -l) )); then
            echo "Coverage is less than previous coverage: $PREVIOUS_COVERAGE%"
            exit 1  # Fail the job
          fi
          echo "$COVERAGE_PERCENTAGE" > last_coverage.txt

      - name: commit and push last_coverage.txt
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated test coverage update"
          git push
  

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: backend/coverage/index.html
      
      # - name: Install dependencies
      #   run: |
      #     cd frontend
      #     npm ci
      # - name: Run tests
      #   run: |
      #     cd frontend
      #     npm run cy:test
