# github action to run ci/cd pipeline on push
name: test-coverage-and-format

on:
  push:
    branches:
      - main
      - feat**
  # pull_request:
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run tests and check coverage difference
        id: coverage-check
        run: |
          cd backend
          npm run test
      
          COVERAGE_PERCENTAGE=$(cat coverage/index.html | grep -oP "(?<=<span class=\"strong\">)\d+\.\d+(?=%)" | head -1)
          echo "Coverage Percentage: $COVERAGE_PERCENTAGE"

          value=`cat last_coverage.txt`
          PREVIOUS_COVERAGE=$(echo $value)
          echo "Previous Coverage: $PREVIOUS_COVERAGE"

          if (( $(echo "$COVERAGE_PERCENTAGE < $PREVIOUS_COVERAGE" | bc -l) )); then
            echo "Coverage is less than previous coverage: $PREVIOUS_COVERAGE%"
            exit 1  # Fail the job
          fi

          if (( $(echo "$COVERAGE_PERCENTAGE == $PREVIOUS_COVERAGE" | bc -l) )); 
          then
            echo "Coverage is same: $PREVIOUS_COVERAGE%"
            echo "modified=false" >> $GITHUB_OUTPUT
          else
            echo "modified=true" >> $GITHUB_OUTPUT
          fi

          echo "$COVERAGE_PERCENTAGE" > last_coverage.txt

      # - name: commit and push last_coverage.txt
      #   if: steps.coverage-check.outputs.modified == 'true'
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #     git commit -am "Automated test coverage update"
  

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: backend/coverage/index.html
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install formatter
        run: |
          npm install -g prettier

      - name: Format files
        run: |
          prettier --write backend/src/**/*.ts
          prettier --write frontend/src/**/*.{ts,tsx}
          prettier --write frontend/src/*.tsx
        
      - name: Check for modified files
        id: format-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.format-check.outputs.modified == 'true' || steps.coverage-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated changes by github action"  
          git push
