# github action to run ci/cd pipeline on push
name: build-test-deploy

on:
  push:
    branches:
      - main
      - feature*
  workflow_dispatch:

jobs:
  
  build-test-deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Install dependencies
      #   run: |
      #     cd backend
      #     npm ci

      # - name: Run tests
      #   run: |
      #     cd backend
      #     npm run test
      #   # job fail if coverage rate less than 60%
      
      # # - name: Install dependencies
      # #   run: |
      # #     cd frontend
      # #     npm ci
      # # - name: Run tests
      # #   run: |
      # #     cd frontend
      # #     npm run cy:test
      #   # job fail if coverage rate less than 60% 

      # - name: Build and push Docker image
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:latest ./frontend
      #     docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:latest ./backend
      #     docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:latest
      #     docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:latest

  deploy-k8s:
    needs: build-test-deploy-docker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v4

      - uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}


      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            k8s/services.yaml
            k8s/deploys.yaml
          images: |
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-app:latest
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/todo-ui:latest
          skip-tls-verify: true
    