name: Format

on:
  push:
    branches:
      - main
      - feature*
  workflow_dispatch:

  # Auto run formatter and create new commit for formatting.
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install formatter
        run: |
          npm install -g prettier

      - name: Format files
        run: |
          prettier --write backend/src/**/*.ts
          prettier --write frontend/src/**/*.{ts,tsx}
        
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated changes by formatter action"
          git push
